const {chromium}=require('playwright');const fs=require('node:fs');const path=require('node:path');
(async()=>{const root=path.resolve(__dirname,'../..'),base=process.env.TEST_WEB_URL||'http://127.0.0.1:3000';const values={};for(const line of fs.readFileSync(path.join(root,'.local/dev.env'),'utf8').split('\n')){const m=line.match(/^export ([A-Z_]+)=(.*)$/);if(m)values[m[1]]=m[2].replace(/^'|'$/g,'')}
 const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});try{const page=await browser.newPage({viewport:{width:1250,height:1050}});const errors=[];page.on('pageerror',e=>errors.push(e.message));let registered=false,posted=false;
 await page.route('**/api/control/status',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({roles:['admin'],github_owner:true,github_app_configured:registered,github_app_connected:registered,github_app_slug:registered?'fixture-deploy':'',github_configured:registered,github_connected:registered})}));
 await page.route('**/api/control/github/app/register',r=>{if(r.request().method()!=='POST'||r.request().postDataJSON().organization!=='test-org')throw Error('Organization selection not sent');return r.fulfill({contentType:'application/json',body:JSON.stringify({action:'https://github.com/organizations/test-org/settings/apps/new?state=browser-fixture',manifest:{name:'Fixture deploy',public:false,default_permissions:{contents:'read',pull_requests:'read'}}})})});
 await page.route('https://github.com/organizations/test-org/settings/apps/new?state=browser-fixture',async r=>{const fields=new URLSearchParams(r.request().postData());const manifest=JSON.parse(fields.get('manifest'));if(r.request().method()!=='POST'||manifest.public!==false||manifest.default_permissions.contents!=='read')throw Error('Manifest form was not submitted');posted=true;await r.fulfill({contentType:'text/html',body:'<h1>GitHub registration fixture</h1>'})});
 await page.goto(base+'/login.html');await page.fill('[name=email]',values.CONTROL_USER);await page.fill('[name=password]',values.CONTROL_PASSWORD);await page.getByRole('button',{name:'Open workspace'}).click();await page.waitForURL('**/console.html');await page.locator('[data-tab=settings]').click();await page.waitForSelector('#connect');if(await page.locator('[name=client_id],[name=client_secret]').count())throw Error('Manual OAuth credentials still required');
 await page.fill('#github-organization','test-org');fs.mkdirSync(path.join(root,'.local/screenshots/github-app'),{recursive:true});await page.screenshot({path:path.join(root,'.local/screenshots/github-app/connect.png'),fullPage:true});await page.locator('#connect').click();await page.waitForURL('https://github.com/organizations/test-org/settings/apps/new?state=browser-fixture');if(!posted)throw Error('GitHub form blocked by CSP');
 registered=true;await page.route('**/api/control/github/app/install',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({url:'https://github.com/apps/fixture-deploy/installations/new?state=install-fixture'})}));await page.route('https://github.com/apps/fixture-deploy/installations/new?state=install-fixture',r=>r.fulfill({contentType:'text/html',body:'<h1>GitHub repository selection fixture</h1>'}));await page.goto(base+'/console.html?github=registered');await page.getByRole('button',{name:'Choose repositories',exact:true}).waitFor();await page.getByRole('button',{name:'Choose repositories',exact:true}).click();await page.waitForURL('https://github.com/apps/fixture-deploy/installations/new?state=install-fixture');if(errors.length)throw Error('Browser errors: '+errors.join(', '));console.log('PASS: GitHub App GUI has no manual OAuth fields, submits a manifest through allowed CSP, supports organization ownership and opens repository selection; GitHub endpoints are browser fixtures');
 }finally{await browser.close()}})().catch(e=>{console.error(e.message);process.exitCode=1});
