const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});try{const p=await b.newPage();let claimed=false,calls=0;const token='fixture-operator-token-'+ 's'.repeat(40);
await p.route('**/api/control/*',r=>{const n=new URL(r.request().url()).pathname.split('/').pop();return r.fulfill({json:n==='status'?{roles:['admin']}:n==='apps'?[{id:'fixture',domain:'fixture.example.com',repository:'owner/app',branch:'main',current:{commit:'abc'}}]:n==='deployments'?{deployments:[]}:[]})});
await p.route('**/api/control/apps/*/owner-claim',r=>{calls++;assert.equal(r.request().method(),'POST');return r.fulfill({json:claimed?{state:'claimed'}:{state:'unclaimed',token}})});
await p.goto((process.env.TEST_WEB_URL||'http://127.0.0.1:8879')+'/console.html');await p.locator('.app-card').first().waitFor();await p.evaluate(()=>{status.roles=['admin'];render()});await p.locator('.app-more summary').first().click();await p.locator('[data-owner-claim]').first().click();assert.equal(calls,0,'Token automatically fetched');
// Verify the permission-gated POST flow without exposing tokens on routine refresh.
await p.locator('#reveal-owner-token').click();await p.locator('[aria-label="One-time operator setup token"]').waitFor();assert.equal(calls,1);assert.equal(await p.locator('[aria-label="One-time operator setup token"]').inputValue(),token);await p.locator('#feature-close').click();await p.waitForFunction(()=>!document.querySelector('[aria-label="One-time operator setup token"]'));assert.equal(await p.locator('[aria-label="One-time operator setup token"]').count(),0,'Closed dialog retained secret');
claimed=true;await p.locator('[data-owner-claim]').first().click();await p.locator('#reveal-owner-token').click();await p.getByText('This app has already been claimed. No setup token is available.').waitFor();assert.equal(await p.locator('[aria-label="One-time operator setup token"]').count(),0);await p.locator('#feature-close').click();
await p.evaluate(()=>{status.roles=['viewer'];render()});assert.equal(await p.locator('[data-owner-claim]').count(),0,'Viewer sees secret action');console.log('PASS: explicit reveal, secret cleared on close, viewer action hidden');}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
