const {chromium}=require('playwright');
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
(async()=>{
 const root=path.resolve(__dirname,'../..'),base=process.env.TEST_WEB_URL||'http://127.0.0.1:3000';
 const cfg={};for(const line of fs.readFileSync(path.join(root,'.local/dev.env'),'utf8').split('\n')){const m=line.match(/^export ([A-Z_]+)=(.*)$/);if(m)cfg[m[1]]=m[2].replace(/^'|'$/g,'')}
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_BIN||'/usr/bin/chromium',headless:true,args:['--no-sandbox']});let member,subject;
 const owner=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];owner.on('pageerror',e=>errors.push(e.message));
 const email='team-'+crypto.randomBytes(6).toString('hex')+'@example.com',password='Fixture-'+crypto.randomBytes(16).toString('hex'),headers={Origin:base};
 async function login(page,email,password){await page.goto(base+'/login.html');await page.fill('[name=email]',email);await page.fill('[name=password]',password);await page.click('button[type=submit]');await page.waitForURL('**/console.html');await page.waitForFunction(()=>document.body.dataset.role)}
 try{
 await login(owner,cfg.CONTROL_USER,cfg.CONTROL_PASSWORD);await owner.click('[data-tab=team]');await owner.waitForSelector('#team-form');await owner.fill('#team-form [name=email]',email);await owner.fill('#team-form [name=name]','Browser member');await owner.fill('#team-form [name=password]',password);await owner.selectOption('#team-form [name=role]','viewer');const save=owner.waitForResponse(r=>r.url().endsWith('/api/control/team')&&r.request().method()==='POST');await owner.click('#team-form button[type=submit]');const saved=await save;if(!saved.ok())throw Error('Team save failed: '+await saved.text());subject=(await saved.json()).subject;await owner.waitForFunction(email=>document.querySelector('#content')?.textContent.includes(email),email);if(await owner.locator('#team-form [name=password]').inputValue())throw Error('Password stayed in the team form');
 const context=await browser.newContext();member=await context.newPage();member.on('pageerror',e=>errors.push(e.message));await login(member,email,password);if(await member.locator('#new-app').isVisible()||await member.locator('[data-tab=team]').isVisible())throw Error('Viewer saw admin controls');let response=await member.request.post(base+'/api/control/servers',{headers,data:{}});if(response.status()!==403)throw Error('Viewer reached infrastructure');
 await owner.click('[data-member-edit="'+subject+'"]');await owner.selectOption('#team-form [name=role]','deployer');const update=owner.waitForResponse(r=>r.url().endsWith('/api/control/team')&&r.request().method()==='POST');await owner.click('#team-form button[type=submit]');if(!(await update).ok())throw Error('Role update failed');await member.reload();await member.waitForFunction(()=>document.body.dataset.role==='deployer');if(await member.locator('#new-app').isVisible())throw Error('Deployer saw app provisioning control');
 await owner.click('[data-tab=audit]');await owner.waitForFunction(()=>document.querySelector('#content')?.textContent.includes('team.member.set'));const audit=await (await owner.request.get(base+'/api/control/audit')).text();if(audit.includes(password))throw Error('Audit leaked the member password');fs.mkdirSync(path.join(root,'.local/screenshots'),{recursive:true});await owner.screenshot({path:path.join(root,'.local/screenshots/audit.png'),fullPage:true});
 await owner.click('[data-tab=team]');await owner.waitForSelector('[data-member-remove="'+subject+'"]');owner.once('dialog',d=>d.accept());const removal=owner.waitForResponse(r=>r.url().endsWith('/api/control/team/'+subject)&&r.request().method()==='DELETE');await owner.click('[data-member-remove="'+subject+'"]');if(!(await removal).ok())throw Error('Membership removal failed');if((await member.request.get(base+'/api/control/apps')).status()!==403)throw Error('Removed member retained access');subject=null;
 if(errors.length)throw Error(errors.join('\n'));console.log('PASS: GUI creates a password account, changes viewer to deployer, hides privileged controls, displays safe audit events, and revokes a live session');
 }finally{if(subject)await owner.request.delete(base+'/api/control/team/'+subject,{headers});await browser.close()}
})().catch(e=>{console.error(e);process.exit(1)});
