const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});try{
const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[],calls=[];page.on('pageerror',e=>errors.push(e.message));
let data={control_version:'v0.2.14',settings:{automatic:false,latest:'v0.2.15',checked:'2026-10-10T03:00:00Z',targets:[]},servers:[{server_id:'local',name:'This server',local:true,current:'v0.2.14',supported:true,state:'idle'},{server_id:'remote',name:'Remote host',local:false,current:'v0.2.14',supported:true,state:'idle'}]},offline=false;
await page.route('**/api/control/**',async route=>{const path=new URL(route.request().url()).pathname,method=route.request().method();
 if(path.includes('/updates')){calls.push({path,method,body:route.request().postDataJSON()});if(offline){await route.fulfill({status:503,json:{error:'Updates unavailable'}});return;}if(method==='PATCH')data.settings.automatic=route.request().postDataJSON().automatic;if(path.endsWith('/install'))data.settings.targets=[{server_id:'remote',state:'waiting',message:'Queued remote first'},{server_id:'local',state:'waiting',message:'Control panel last'}];await route.fulfill({json:path.endsWith('/updates')&&method==='GET'?data:data.settings});return;}
 const name=path.split('/').pop();await route.fulfill({json:name==='status'?{roles:['admin']}:name==='deployments'?{deployments:[],unavailable_servers:[]}:name==='servers'?data.servers.map(s=>({id:s.server_id,name:s.name,url:s.local?'http://127.0.0.1:9090':'https://agent.example'})):[]});});
await page.goto((process.env.TEST_WEB_URL||'http://127.0.0.1:8880')+'/console.html#updates');await page.locator('#updates-check').waitFor();assert(await page.getByText('Remote host',{exact:true}).isVisible());assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth),0);
await page.evaluate(()=>window.stableUpdate=document.querySelector('#updates-check'));await page.evaluate(()=>refresh({background:true}));assert(await page.evaluate(()=>stableUpdate===document.querySelector('#updates-check')),'Unchanged update status replaced DOM');
await page.locator('#updates-check').click();assert(calls.some(c=>c.path.endsWith('/updates/check')&&c.method==='POST'));
await page.locator('#updates-auto').check();await page.waitForFunction(()=>document.querySelector('#updates-auto').checked);assert(calls.some(c=>c.method==='PATCH'&&c.body.automatic===true));
await page.locator('#updates-install').click();await page.getByText('Queued remote first',{exact:true}).waitFor();assert(await page.locator('#updates-install').isDisabled());
offline=true;await page.evaluate(()=>loadUpdates());assert(await page.getByText('Queued remote first',{exact:true}).isVisible(),'Offline poll cleared update progress');
await page.locator('#menu-toggle').click();await page.locator('[data-tab=apps]').click();offline=false;await page.locator('#menu-toggle').click();await page.locator('[data-tab=updates]').click();await page.locator('#updates-check').waitFor();assert.equal(errors.length,0,errors.join('\n'));console.log('PASS: mobile update status, release check, automatic policy, fleet queue, stable polling, offline retention and return navigation');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
